###############################################################################
# Secret - Stockage sécurisé des credentials de l'application
###############################################################################
apiVersion: v1
kind: Secret
metadata:
  name: fastapi-app-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fastapi-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.backend.secrets.POSTGRES_PASSWORD | quote }}
  SECRET_KEY: {{ .Values.backend.secrets.SECRET_KEY | quote }}
  FIRST_SUPERUSER: {{ .Values.backend.secrets.FIRST_SUPERUSER | quote }}
  FIRST_SUPERUSER_PASSWORD: {{ .Values.backend.secrets.FIRST_SUPERUSER_PASSWORD | quote }}

